In [1]:
import pandas as pd
import numpy as np

In [2]:
!ls

README.md                  new_feature_dt.csv
bicycle_dataset            new_feature_rfr.csv
bicycle_eda.ipynb          new_poly_dt.csv
bicycle_modeling.ipynb     new_poly_sgd.csv
deep_learning.ipynb        submission.csv
iris dataset               submission_bicycle.csv
iris_LazyRegressor.ipynb   submission_bicycle_dt.csv
iris_eda.ipynb             submission_bicycle_rfr.csv
iris_modeling.ipynb        submission_lasso.csv
new_combi_feature_dt.csv   submission_rfr.csv
new_combi_feature_rfr.csv  submission_test.csv
new_combi_feature_xgb.csv

In [3]:
train = pd.read_csv('iris_dataset/train.csv')

In [4]:
train.head(5)

,id,species,sepal length (cm),petal length (cm),sepal width (cm),petal width (cm)
0,0,setosa,4.4,1.4,2.9,0.2
1,1,versicolor,6.4,4.5,3.2,1.5
2,2,virginica,6.2,4.8,2.8,1.8
3,3,virginica,7.2,6.1,3.6,2.5
4,4,setosa,4.9,1.4,3.0,0.2

In [5]:
train.describe()

,id,sepal length (cm),petal length (cm),sepal width (cm),petal width (cm)
count,75.000000,75.000000,75.000000,75.000000,75.000000
mean,37.000000,6.044000,4.258667,2.958667,1.384000
std,21.794495,0.842653,1.615390,0.388376,0.697106
min,0.000000,4.300000,1.100000,2.000000,0.100000
25%,18.500000,5.550000,3.750000,2.800000,1.000000
50%,37.000000,6.100000,4.700000,3.000000,1.500000
75%,55.500000,6.600000,5.300000,3.200000,1.850000
max,74.000000,7.700000,6.900000,4.000000,2.500000

In [6]:
train['species'] = train['species'].map({'setosa':0, 'versicolor':1, 'virginica':2})

In [8]:
test = pd.read_csv('iris_dataset/test.csv')

In [10]:
test.head(5)

   id    species  sepal length (cm)  petal length (cm)
0   0     setosa                5.4                1.7
1   1     setosa                5.7                1.5
2   2     setosa                5.3                1.5
3   3     setosa                5.1                1.9
4   4  virginica                6.0                4.8

In [11]:
test.describe()

              id  sepal length (cm)  petal length (cm)
count  75.000000          75.000000          75.000000
mean   37.000000           5.642667           3.257333
std    21.794495           0.767441           1.776816
min     0.000000           4.400000           1.000000
25%    18.500000           5.100000           1.500000
50%    37.000000           5.500000           3.700000
75%    55.500000           6.150000           5.050000
max    74.000000           7.900000           6.400000

In [12]:
test['species'] = test['species'].map({'setosa':0, 'versicolor':1, 'virginica':2})

In [16]:
from lazypredict.Supervised import LazyRegressor
from sklearn import datasets
from sklearn.utils import shuffle
import numpy as np
from sklearn.model_selection import train_test_split

In [17]:
X = train[['species', 'sepal length (cm)', 'petal length (cm)']]
y = train[['sepal width (cm)', 'petal width (cm)']]

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [20]:
def MAE(true, pred):
    score = np.mean(np.abs(true-pred))
    return score

In [22]:
reg = LazyRegressor(verbose = 0, ignore_warnings=True, custom_metric=MAE)
models, predictions = reg.fit(X_train, X_test, y_train, y_test)
models

100%|██████████| 42/42 [00:00<00:00, 139.43it/s]

,R-Squared,RMSE,MAE,Time Taken
Model,,,,
TransformedTargetRegressor,0.68,0.23,sepal width (cm) 0.22 petal width (cm) 0.1...,0.00
Lars,0.68,0.23,sepal width (cm) 0.22 petal width (cm) 0.1...,0.01
LinearRegression,0.68,0.23,sepal width (cm) 0.22 petal width (cm) 0.1...,0.00
RidgeCV,0.68,0.23,sepal width (cm) 0.22 petal width (cm) 0.1...,0.01
Ridge,0.67,0.23,sepal width (cm) 0.22 petal width (cm) 0.1...,0.00
KNeighborsRegressor,0.63,0.24,sepal width (cm) 0.23 petal width (cm) 0.1...,0.01
RANSACRegressor,0.63,0.24,sepal width (cm) 0.23 petal width (cm) 0.1...,0.01
OrthogonalMatchingPursuit,0.49,0.29,sepal width (cm) 0.25 petal width (cm) 0.1...,0.00
RandomForestRegressor,0.47,0.29,sepal width (cm) 0.27 petal width (cm) 0.1...,0.05
BaggingRegressor,0.41,0.30,sepal width (cm) 0.29 petal width (cm) 0.1...,0.02
ExtraTreesRegressor,0.31,0.32,sepal width (cm) 0.31 petal width (cm) 0.1...,0.03
ExtraTreeRegressor,0.24,0.36,sepal width (cm) 0.33 petal width (cm) 0.2...,0.00
ElasticNet,0.12,0.50,sepal width (cm) 0.27 petal width (cm) 0.5...,0.01
LassoLars,-0.03,0.58,sepal width (cm) 0.27 petal width (cm) 0.6...,0.00
DummyRegressor,-0.03,0.58,sepal width (cm) 0.27 petal width (cm) 0.6...,0.01
Lasso,-0.03,0.58,sepal width (cm) 0.27 petal width (cm) 0.6...,0.00
DecisionTreeRegressor,-0.08,0.41,sepal width (cm) 0.39 petal width (cm) 0.2...,0.01
MLPRegressor,-1.12,0.52,sepal width (cm) 0.58 petal width (cm) 0.1...,0.04
KernelRidge,-37.92,2.34,sepal width (cm) 2.97 petal width (cm) 1.4...,0.01
GaussianProcessRegressor,-417.40,7.13,sepal width (cm) 4.23 petal width (cm) 0.7...,0.01

In [23]:
from sklearn.linear_model import RANSACRegressor

In [26]:
test = test[['species', 'sepal length (cm)', 'petal length (cm)']]
reg = RANSACRegressor(random_state=0).fit(X,y)
reg.score(X,y)

0.6344101225361536

In [27]:
predict = reg.predict(test)

In [28]:
predict

array([[3.45350001, 0.2786458 ],
       [3.72760059, 0.23780715],
       [3.48679248, 0.22665065],
       [3.17939943, 0.31948445],
       [2.97092834, 1.89849883],
       [2.71028254, 1.96672963],
       [3.54699451, 0.22943977],
       [3.35293365, 0.19368026],
       [3.24598437, 0.21549415],
       [2.80847964, 1.40447736],
       [3.29273162, 0.19089114],
       [3.23252959, 0.18810202],
       [3.01129267, 1.98067525],
       [3.36681087, 2.3451404 ],
       [2.70791328, 1.31951182],
       [3.05803992, 1.95607223],
       [3.11212554, 0.18252377],
       [3.37250484, 1.99740999],
       [2.82193442, 1.43186949],
       [2.65715237, 2.09811206],
       [2.83775845, 2.10647944],
       [2.99879335, 0.31111708],
       [2.81486256, 1.29769793],
       [3.31964118, 0.24567542],
       [2.8814475 , 1.19370763],
       [3.13903509, 0.23730804],
       [3.27289393, 0.27027843],
       [3.4733377 , 0.19925851],
       [3.64048901, 0.18023375],
       [3.23226309, 2.07121903],
       [2.96855908, 1.25128103],
       [3.42659045, 0.22386153],
       [3.03846873, 0.15234251],
       [2.93832482, 2.19144497],
       [3.08494948, 2.01085651],
       [3.36638843, 0.2210724 ],
       [3.09867076, 0.15513163],
       [2.76811531, 1.32230094],
       [3.25943915, 0.24288629],
       [3.13639934, 1.47320725],
       [3.36638843, 0.2210724 ],
       [3.3996809 , 0.16907725],
       [3.20604248, 2.25738574],
       [3.25943915, 0.24288629],
       [3.38664857, 2.26575312],
       [3.29911453, 0.08411172],
       [2.8108489 , 2.05169516],
       [2.76742636, 1.08134996],
       [3.63410609, 0.28701317],
       [3.02237819, 1.36084958],
       [3.25943915, 0.24288629],
       [2.55421675, 1.36592872],
       [2.83470025, 1.21831064],
       [2.44726748, 1.38774261],
       [3.70069103, 0.18302287],
       [2.52799615, 1.55209543],
       [3.65394378, 0.20762588],
       [2.75466053, 1.29490881],
       [3.44642815, 0.14447424],
       [3.03583297, 1.38824171],
       [2.97161729, 2.13944982],
       [2.74120575, 1.26751667],
       [3.01836454, 2.11484681],
       [2.8845057 , 2.08187642],
       [3.07883307, 0.23451892],
       [3.36638843, 0.2210724 ],
       [3.20535353, 2.01643476],
       [3.41313567, 0.19646939],
       [3.42659045, 0.22386153],
       [2.76811531, 1.32230094],
       [2.92181183, 1.27588404],
       [3.03846873, 0.15234251],
       [2.77755643, 2.10369031],
       [2.96787013, 1.01033004],
       [2.77048456, 1.96951875]])